### PR TITLE
Fix the bug on copy operation and add test

### PR DESCRIPTION
**Pull request by invkrh**
Fix the bug on `copy` operation and add test

### CODE REVIEW

**Comment by invkrh** [comment]
It seems that travis encountered `sbt.ForkMain$ForkError`

**Comment by invkrh** [comment]
sbt build encounted `Cause: java.lang.NoSuchMethodException: scala.util.Sorting$.sort1([I, int, int)`
It is because `sort1` does not exist in some scala version like 2.11.7.
Since scalaTest is add to deps, it upgrades scala version to 2.11.7

```
Scala version was updated by one of library dependencies:
[warn]  * org.scala-lang:scala-library:(2.11.5, 2.11.0, 2.11.1) -> 2.11.7
```

So the build failed.

It would be better to write the quickSort by hand instead of calling a func by reflect which depends scala version.

A workaround here is to force sbt to use 2.11.5.

**Comment by invkrh** [comment]
@axel22 @vkuncak  Could you review this pr ?

**Comment by axel22** [comment]
LGTM - your PR is in a great state! Thank you very much for contributing!

**Pull request merged**
